### ISSUE TITLE
Unserialize exception.

### ISSUE THREAD

**Issue by inet20** [phpDocumentor/phpDocumentor2#1424]
Not sure whether it's phpDoc issue.
I have php file with comments containing cyryllic symbols. File encoding is UTF-8.
After starting phpdoc I get an error:

Storing cache in "/var2/dev/git/doc" .. OK
Load cache                                                         ..
  [Zend\Serializer\Exception\RuntimeException]
  Unserialization failed
  [ErrorException]
  unserialize(): Error at offset 2663 of 2669 bytes

**Comment by mvriel** [comment]
I have had no new reports for this issue; perhaps it does have something to do with a specific configuration part on your system? phpDocumentor does try to use igbinary, do you have that installed?

**Comment by tokarev-yuriy** [comment]
I have the same issue. 
As far as I understand unserialize works fine, error occurs because of wrong cache data.

And cache is wrong because of some mbstring options: mbstring.internal_encoding = UTF-8 and mbstring.func_overload = 2.

With mbstring.func_overload=2 the cache seems cutted but with another values (mbstring.internal_encoding = latin-1 and mbstring.func_overload = 0) everything works perfect!

Original file:
![orig](https://cloud.githubusercontent.com/assets/1980829/8431482/6f5a78e8-1f42-11e5-9326-802d599970f2.png)

Cached data:
![cache](https://cloud.githubusercontent.com/assets/1980829/8431483/6f5acd8e-1f42-11e5-85bc-bc58d92f0948.png)
