### ISSUE TITLE
{@inheritdoc} not working with interfaces

### ISSUE THREAD

**Issue by sagaraspl** [phpDocumentor/phpDocumentor2#1505]
Hi, {@inheritdoc} not working with interfaces. I am using the version 2.8.1. It is not automatically inheriting @param, @return etc... at method level.

**Comment by nickygerritsen** [comment]
I also seem to have this problem. The actual @param etc are inherited, but I get a long list of errors that parameters are missing, etc. Leaving out {@inheritdoc} (and thus not adding any comment) does the exact same thing

**Comment by sagaraspl** [comment]
Hi, any one from phpDocumentor? When can we get fix of above error?

**Comment by mvriel** [comment]
Hello @sagaraspl, I am currently on a temporary hiatus to recharge my batteries after working a few years on phpDocumentor. Once I get back on the job I will take a look at this item but until then we depend on a contribution to solve this issue. Thank you for your patience

**Comment by thebeline** [comment]
@mvriel - Any pointers on where to look, or what may be going on, to get someone started on hammering this one out?

**Comment by thebeline** [comment]
@sagaraspl - What would be expected behaviour for this?

Say you have a class:
```
class D extends C implements B, A
```

Would it be expected that, for a given method/property, the docblock contents precedence would be:
`D overrides C overrides B overrides A`

It would be important to note that if an interface implements another interface, it would override the docs of the parent interface.  You then start to get into complex situations where C could also implement A, having a docblock for one of A's properties/methods, in which case, C+A would override B.

I don't know, I can see this getting fairly complex fairly quickly.

Either way, I want to look into this if I can, I just need a little guidance on where to start.

**Comment by thebeline** [comment]
@mvriel - I can confirm that, in addition to `{@inheritdoc}` remaining as plain-text on methods that are implemented from Interfaces, if a method is implemented with additional `@param` tags, the implemented `@param` tags will not inherit:

```
interface A {
    /**
     * @param string $a The Interface param.
     */
    function test($a);
}

class B implements A {
    ./**
     * @param int $b The Implemented param
     */
    function test($a, $b) {
        // .....
    }
}
```

The documentation for Param `$a` will not populate in the resulting documentation.

Is this expected behavior?  It would seem, from PHPDoc2's [documentation](http://www.phpdoc.org/docs/latest/guides/inheritance.html#methods) the omitted `@param` tags would auto-populate.  Or is the documentation suggesting that that only occurs if no `@param` tags are present?

**Comment by robertmain** [comment]
This looks to have returned(but only when working with code from outside my project).

**Comment by jaapio** [comment]
Inheritdoc only works on analyzed code. So you have to process your vendor directory to have this working. We can't inherit from what we don't have.

**Comment by robertmain** [comment]
Right, ok. I guess that kinda makes sense...
