### ISSUE TITLE
@return string[] misinterpreted as array<mixed,string>

### ISSUE THREAD

**Issue by evought** [phpDocumentor/phpDocumentor2#1507]
The following docblock in an interface:

```
/**
 * Returns the list of fields specified for this property.
 * 
 * @return string[]
 */
public function getAllowedFields();
```

does not generate the correct documentation for the type in 2.8.1. It comes out as:

```
getAllowedFields() : array<mixed,string>
```

**Comment by mvriel** [comment]
`string[]` and `array<mixed,string>` were equal in the most recent PSR-5 draft. Due to some discussions that are going on the latter syntax is no longer preferable in PSR-5 and will be replaced.

So: technically there is not an error but we have been too fast with adopting features of PSR-5 that were still in draft.

We should change the output to show a more accurate representation

**Comment by jaapio** [comment]
behavior has been changed in v3.0.0-alpha.

**Comment by janareddymareddy** [comment]
Hi jaapio can you please mention what the changes need to be done in 2.9.1 for this. we tried with V3.0.0 but this version not working fine with my project

**Comment by jaapio** [comment]
I think this was the commit: https://github.com/phpDocumentor/phpDocumentor/commit/63ab3014b2e9e555bff9ffdf8fb3a28d280a3171#diff-eec714414aff322d1b44f77a162c5287fe510df4cf148e70d8367e56a02383b1

But as I told you before, please let us know what the issue with v3 is, because we cannot give active support for v2.

**Comment by janareddymareddy** [comment]
Jaapio,

i have attached the XML output on https://github.com/phpDocumentor/phpDocumentor/issues/2965
