### ISSUE TITLE
Installation on shared server?

### ISSUE THREAD

**Issue by alve89** [phpDocumentor/phpDocumentor2#1531]
Is phpDoc installable on a shared server? If yes, which file has to be called to run the software?

**Comment by drewbaker** [comment]
It says this on the homepage of PhpDoc, but I can't get it to work:

```
To do a manual installation, follow these steps

    Locate the latest release on the releases page for phpDocumentor2 on GitHub
    Download the attached tarball (not the source code!)
    Extract the downloaded tarball into your destination directory.

After you have done the above can the executable be found at bin/phpdoc.php in the installation directory.
```

**Comment by mvriel** [comment]
Hi @drewbaker and @alve89,

You can run phpDocumentor on a shared server but please bear in mind that it does not have a web interface and can only be ran from the command line.

So, once you have downloaded and unpacked phpDocumentor you will need to log in to your server using SSH (check with your shared host if you have SSH access):

    $ ssh myserver.com

and then go to the folder where you installed phpDocumentor:

    $ cd /my/folder/where/I/installed/phpDocumentor

and finally execute phpDocumentor like this:

  $ ./bin/phpdoc -d /path/to/project/to/document -t /path/where/to/generate/docs

> please note that the dollar signs ($) above are only meant to illustrate that these are command line commands and should not be typed.

If this still does not work, please post the output here so that I can see what might be going wrong

**Comment by alve89** [comment]
Alright, thank you for this information! Do you think it was possible to implement a simple web interface for generating documents?

**Comment by jaapio** [comment]
Closing this issue due a large delay of responses. Feel free to open a new issue when applicable
