### ISSUE TITLE
Tag, null given

### ISSUE THREAD

**Issue by Tjorriemorrie** [phpDocumentor/phpDocumentor2#1666]
I'm running the phpdoc on the develop branch, and it gives me this error:

> PHP Catchable fatal error:  Argument 1 passed to phpDocumentor\Reflection\DocBlock::addTag() must implement interface phpDocumentor\Reflection\DocBlock\Tag, null given, called in /vagrant/vendor/phpdocumentor/reflection-docblock/src/DocBlock.php on line 68 and defined in /vagrant/vendor/phpdocumentor/reflection-docblock/src/DocBlock.php on line 216

As I understood I must fork the develop branch, but it's not in a working state? Can anyone please clarify

**Comment by Tjorriemorrie** [comment]
phpunit works fine, though

**Comment by jaapio** [comment]
This issue is solved. But please be aware of the fact that phpdocumentor 3 is still in development. It is not a working application at the moment. So I don't know what you are trying to do with it.

If you want to use phpdocumentor please use our latest tagged version. Or have a look at our releases page:
https://github.com/phpDocumentor/phpDocumentor2/releases

**Comment by Tjorriemorrie** [comment]
This is confusing me now, your contrib doc states I must branch develop for each issue.

**Comment by jaapio** [comment]
we are currently working on a new release. I understand that this is a bit confusing. But the develop branch is unstable at the moment. It is still a lot of work before we will release version 3.0.0. Which is in develop.

If you had issues with a released version please create a patch on master.

**Comment by Tjorriemorrie** [comment]
OK, thanks
