### ISSUE TITLE
PHP7 support?

### ISSUE THREAD

**Issue by guoxiao** [phpDocumentor/phpDocumentor2#1701]
Does phpDocumentor2 officially support PHP7 or is there any plan to support PHP7?

I tried running phpDocumentor2 with PHP7 and met the problem:
```
PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in phar:///home/guoxiao/bin/phpDocumentor.phar/vendor/jms/serializer/src/JMS/Serializer/XmlDeserializationVisitor.php:62
```

**Comment by mvriel** [comment]
Hello @guoxiao,

We currently do not officially support PHP 7 though this is planned for phpDocumentor 3 and we intend to explore how much work it is to enable this for phpDocumentor 2.

The error that you mention however is not due to a problem with phpDocumentor but because the libxml/DOM extension is not enabled in your PHP installation; please see http://php.net/manual/en/book.dom.php for more information on this.

As far as I know this extension is enabled by default, even in PHP7. Perhaps you can check if your installation is complete and/or libxml is enabled?

**Comment by guoxiao** [comment]
Hi, mvriel.

Thank you for your help. I enabled `dom` and `simplexml` extension and the previous issue is gone. However I have another error now:
```
Collecting files .. OK
Initializing parser .. OK
Parsing files
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Monolog\ErrorHandler::handleException() must be an instance of Exception, instance of Error given in phar:///home/guoxiao/bin/phpDocumentor.phar/vendor/monolog/monolog/src/Monolog/ErrorHandler.php:122
Stack trace:
#0 [internal function]: Monolog\ErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in phar:///home/guoxiao/bin/phpDocumentor.phar/vendor/monolog/monolog/src/Monolog/ErrorHandler.php on line 122
```

**Comment by jaapio** [comment]
I think we have to create a new release for this. Monolog's interface has been changed.
https://github.com/Seldaek/monolog/commit/b941eac988decda854947b297c8357c5dac612e8

But like @mvriel we do not officially support php7.

**Comment by rgeraads** [comment]
We might want to put in the composer.json that `ext-xml` is required.

**Comment by jaapio** [comment]
I just checked this. PhpDocumentor seem to work fine on php7.0. We still need to create a new tag since I tested this with the latest master version.

**Comment by quantumpacket** [comment]
@jaapio Don''t forget https://github.com/phpDocumentor/phpDocumentor2/issues/1705 and https://github.com/phpDocumentor/phpDocumentor2/issues/1706 are PHP7 specific issues. I've tested on PHP5 and they work, but then break with PHP7. Tested using PhpDoc master. Can you confirm these as well and label them for PHP7?

**Comment by jaapio** [comment]
We will not support php 5.5+ syntaxes for now. You should be able to run phpdocumentor 2 on php7. But I have to have a look at the reflection component and the usage of nikic/PHP-Parser. Since there where a number of interface changes in nikic/PHP-Parser the 0.9.5 version is not compatible with the 1.0 + version. of that library. That is where this parser error is coming from. Since 0.9.5 only supports php 5.5.

Upgrading to a newer version should be possible with minimal effort however we will not support any new language constructions.

**Comment by wham** [comment]
I can confirm that code from the master works with PHP 7. Please are you planning any more 2.X.X releases?

**Comment by mvriel** [comment]
Yes, we actually wanted to do one two weeks ago but I had to cancel that at the last moment. I intend on doing a new release next saturday

**Comment by slash3b** [comment]
@guoxiao I had the same problem. 
My PHP version:
```
PHP 7.0.4 (cli) (built: Mar  2 2016 17:31:49) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

```

just `sudo dnf install php-xml ` or `sudo apt-get install php-xml`. It worked for me.

**Comment by alpharder** [comment]
@mvriel Any news on the release with PHP7 support?

**Comment by ZacharyDuBois** [comment]
Same question, it'd be nice to fix that error in the homebrew build.

**Comment by jaapio** [comment]
Hello Everyone, 

I'm working on a new release of phpdocumentor-2 with php-7 compatibility. This version is now available in master. It would be very helpful if you could test with this version if your issues are solved. We would be very happy to get your feedback.

**Comment by emeraldinspirations** [comment]
Hello @jaapio,

I just successfully used the most recent version.  It was quite a hassle in setting up requiring lots of searching through forums, as well as some trial and error.  Therefore, I decided to detail the steps I used below so that perhaps it would help someone else.

* **Git commit**: https://github.com/phpDocumentor/phpDocumentor2/commit/4ef8bc86fad4c0e104d38e01016055e9e43b409d
* **Oporating System version**: Ubuntu 16.10
* **PHP version**: 7.0.8-3ubuntu3

Steps I took:

1. I cloned the repo `git clone git@github.com:phpDocumentor/phpDocumentor2.git`
2. I checked out the master branch `git checkout master`
3. I attempted to run `composer install` had the following error:
```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for behat/behat v3.0.15 -> satisfiable by behat/behat[v3.0.15].
    - behat/behat v3.0.15 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
  Problem 2
    - Installation request for doctrine/instantiator 1.0.2 -> satisfiable by doctrine/instantiator[1.0.2].
    - doctrine/instantiator 1.0.2 requires php ~5.3 -> your PHP version (7.0.8) does not satisfy that requirement.
  Problem 3
    - doctrine/instantiator 1.0.2 requires php ~5.3 -> your PHP version (7.0.8) does not satisfy that requirement.
    - phpunit/phpunit-mock-objects 2.3.8 requires doctrine/instantiator ^1.0.2 -> satisfiable by doctrine/instantiator[1.0.2].
    - Installation request for phpunit/phpunit-mock-objects 2.3.8 -> satisfiable by phpunit/phpunit-mock-objects[2.3.8].

  To enable extensions, verify that they are enabled in those .ini files:
    - /etc/php/7.0/cli/php.ini
    - /etc/php/7.0/cli/conf.d/10-mysqlnd.ini
    - /etc/php/7.0/cli/conf.d/10-opcache.ini
    - /etc/php/7.0/cli/conf.d/10-pdo.ini
    - /etc/php/7.0/cli/conf.d/15-xml.ini
    - /etc/php/7.0/cli/conf.d/20-calendar.ini
    - /etc/php/7.0/cli/conf.d/20-ctype.ini
    - /etc/php/7.0/cli/conf.d/20-curl.ini
    - /etc/php/7.0/cli/conf.d/20-dom.ini
    - /etc/php/7.0/cli/conf.d/20-exif.ini
    - /etc/php/7.0/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.0/cli/conf.d/20-ftp.ini
    - /etc/php/7.0/cli/conf.d/20-gettext.ini
    - /etc/php/7.0/cli/conf.d/20-iconv.ini
    - /etc/php/7.0/cli/conf.d/20-json.ini
    - /etc/php/7.0/cli/conf.d/20-mysqli.ini
    - /etc/php/7.0/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/7.0/cli/conf.d/20-phar.ini
    - /etc/php/7.0/cli/conf.d/20-posix.ini
    - /etc/php/7.0/cli/conf.d/20-readline.ini
    - /etc/php/7.0/cli/conf.d/20-shmop.ini
    - /etc/php/7.0/cli/conf.d/20-simplexml.ini
    - /etc/php/7.0/cli/conf.d/20-sockets.ini
    - /etc/php/7.0/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.0/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.0/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.0/cli/conf.d/20-tokenizer.ini
    - /etc/php/7.0/cli/conf.d/20-wddx.ini
    - /etc/php/7.0/cli/conf.d/20-xmlreader.ini
    - /etc/php/7.0/cli/conf.d/20-xmlwriter.ini
    - /etc/php/7.0/cli/conf.d/20-xsl.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
```
4. I then installed `mbstring` via `sudo apt-get install php-mbstring` per [getting error, while update Composer](http://stackoverflow.com/a/36979121) (Note: `sudo apt-get install libapache2-mod-php5` failed)

5. I then changed the `composer.json` file's require statement
```
...
"require": {
    "php": ">=7.0.0",
...
```

**Comment by infiniweb** [comment]
Steps from emeraldinspirations worked perfectly for me.

For windows users generating the documentation in local, the step 4 is obviously not required as long as the local installation of apache already includes the required elements.

During composer install I faced the following errors:
```
$ composer install
    Loading composer repositories with package information
    Installing dependencies (including require-dev) from lock file
    Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/instantiator 1.0.2 -> satisfiable by doctrine/instantiator[1.0.2].
    - doctrine/instantiator 1.0.2 requires php ~5.3 -> your PHP version (7.0.3) does not satisfy that requirement.
  Problem 2
    - doctrine/instantiator 1.0.2 requires php ~5.3 -> your PHP version (7.0.3) does not satisfy that requirement.
    - phpunit/phpunit-mock-objects 2.3.8 requires doctrine/instantiator ^1.0.2 -> satisfiable by doctrine/instantiator[1.0.2].
    - Installation request for phpunit/phpunit-mock-objects 2.3.8 -> satisfiable by phpunit/phpunit-mock-objects[2.3.8].
```

It has been solved by updating the composer.json as instructed by emeraldinspirations, followed by composer update.

```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing zetacomponents/base (1.9)
```

```
$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
```
