### ISSUE TITLE
@inheritdoc does not work when there are two parents

### ISSUE THREAD

**Issue by tflori** [phpDocumentor/phpDocumentor2#1811]
I have an interface that describes method `doSomething($object): bool`:

```php
interface ExampleInterface 
{
  /**
   * Do something with $object and return that it worked
   *
   * @param \stdClass $object The object 
   * @return bool
   * @internal
   */
  public function doSomething(\stdClass $object);
}
```

And a class that implements this interface:
```php
class Example implements ExampleInterface 
{
  /** {@inheritdoc} */
  public function doSomething(\stdClass $object) 
  {
    // what ever
    return true;
  }
}
```

When I now create a second interface that extends the ExampleInterface we can define additonal methods here:
```php
interface DeepExampleInterface extends ExampleInterface
{
  /**
   * Convert $json to object and doSomething
   *
   * @param string $json
   * @return bool
   */
  public function doSomethingJson($json);
}
```

Now comes the problem. The following class extends `Example` and implements `DeepExampleInterface`. When it overwrites `doSomething()` (which is doing something really special :smile:) and inherits the doc we don't know what doc to inherit.

```php
class DeepExample extends Example implements DeepExampleInterface
{
  /** {@inheritdoc} */
  public function doSomethingJson($json) 
  {
    return $this->doSomething(json_encode($json));
  }

  /** {@inheritdoc} */
  public function doSomething(\stdClass $object) 
  {
    // do something really special
    return true;
  }
}
```

Even now the documentation will be the same, it is not shown. The summary is just `{@inheritdoc}`. In my opinion the inherited documentation from extended class has a higher weight than the one from implemented interface and phpdocumentor should choose this.

*i'm working with phpdocumentor ^2.9*

**Comment by tflori** [comment]
Hm it seams not to be the only problem. It is a very strange behavior for me. It seems that `{@inheritdoc}` is not even recursive. Or something else is wrong. When I add the documentation to the `DeepExample` but omit it from `Example` class it is also not shown. I really don't get it.

Of course the workaround is to add the same documentation in every method.. But it feels very unDRY for me :smile:

**Comment by tflori** [comment]
maybe the problem is to inherit `@internal` documentation... with another method it works better.. anyway: it should work for `@internal` too...

**Comment by jaapio** [comment]
Sounds as a bug for me. Unfortunately I don't have time at the moment to fix this. 

Thanks for reporting this

**Comment by mvriel** [comment]
Please be aware that the notation that you use is an inline notation that only inherits the description of the parent DocBlock. This is a point of confusion that has existed earlier. We are in discussion with other projects to replace `{@inheritDoc}` with an official `@inheritDoc` tag, but also to make phpDocumentor flexible when it comes to the aforementioned tag as long as it is the only tag in the DocBlock.

phpDocumentor performs inheritance by default (see https://phpdoc.org/docs/latest/guides/inheritance.html). However: I do want to investigate what you mention to see if the bubbling of inherited items works as expected. It should but unfortunately this is a very complex part of the application and may inadvertently have been broken somewhere along the line

**Comment by jaapio** [comment]
I added a behat feature to check this behavior. It doesn't work as expected. More tests will be added to insure that we don't break things while fixing this issue.

**Comment by jaapio** [comment]
It took me some time to figure out what was going on here. Like @tflori wrote it has something to do with the `@internal` tag. Like the documentation states. `@internal` are completely ignored. unless you pass the `parseprivate` flag. Which will result in adding the internal elements to the output. 

Because this feature is documented correctly and everything works like expected I'm closing this issue as invalid.

**Comment by NestorAcevedo** [comment]
Version 2.9.0
@inheritdoc not works.
http://docs.phpdoc.org/guides/inheritance.html#the-inheritdoc-tag describes that this tag imports the description of parent element.  Same here: https://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.inlineinheritdoc.pkg.html

But running phpdoc only I see the tag, not the imported description as is supposed to work.

Why can I ensure still is buggy?: because Yii Framework puts the tag on auto-generated models and controllers from gii. Closing the tag in curly braces not works either.

**Comment by jaapio** [comment]
Please try out the new release v3. 0.0-alpha did not check if it works. But it should
