### ISSUE TITLE
Proposed syntax "string[]+int[]" for mixed array types.

### ISSUE THREAD

**Issue by donquixote** [phpDocumentor/phpDocumentor2#1813]
Maybe this is better discussed in the php-fig group. But sometimes interesting discussions happen in this issue queue. So forgive me for posting it here first.

Sometimes I want to document a parameter or return value with a mixed array type, e.g. where some array elements are `string` and others are `int` or perhaps `string[]`.

For my IDE, it is good enough to just say `@param string[]|string[][]|int[] $arr`, with the | for OR. But semantically this is incorrect, because strictly speaking this would mean that the array is either purely `string[]` or `string[][]` or `int[]`, but not mixed.

As a semantically more accurate syntax, I propose to write `@param string[]+string[][]+int[] $arr`.

I think this is a good idea because any such mixed array can be created by combining multiple "pure" arrays with the + operation.

**Comment by Christoph-Harms** [comment]
...or, if you wanted to keep using the `|`, you could do something like

```
/*
 * @param (string|int|string[])[] $arr
 */
```

**Comment by donquixote** [comment]
Oh, now I see your version is already part of the PSR-5 draft:

https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#appendix-a-types

So now I only need to convince the PhpStorm guys to support it.

**Comment by donquixote** [comment]
https://youtrack.jetbrains.com/issue/WI-20193

**Comment by mvriel** [comment]
The suggested syntax to resolve this, as mentioned earlier, is

``` php
(string|int|string[])[]
```

Although I strongly recommend against using such coding constructs from a developer's perspective I do acknowledge that these situations occur and would be nice if they are handled.

I will be closing this issue because at the moment it does not require effort from the phpDocumentor team as far as I am aware. Thank you for mentioning this
