### ISSUE TITLE
Composer installation fails with Symfony 3.2.*

### ISSUE THREAD

**Issue by giovkanata** [phpDocumentor/phpDocumentor2#1818]
My installed version is 3.2.2 but Composer state: Installation request for symfony/symfony (locked at v3.2.1, required as 3.2.*) -> satisfiable by symfony/symfony[v3.2.1].
I don't see much deep but I don't see if we only need to allow a major version to fix this.
Can someone confirm that or have a workaround?

**Comment by fadykstas** [comment]
installation requires Symfony/Validator 2.8.9 which is unsuitable with Symfony 3.2.*

> Problem 1
>     - Installation request for phpdocumentor/phpdocumentor ^2.9 -> satisfiable by phpdocumentor/phpdocumentor[v2.9.0].
>     - phpdocumentor/phpdocumentor v2.9.0 requires symfony/validator ~2.2 -> satisfiable by symfony/validator[2.2.x-dev-2.8.x-dev, v2.2.0-v2.8.9] but these conflict with your requirements or minimum-stability.

**Comment by jaapio** [comment]
Please use the provided [phar](https://github.com/phpDocumentor/phpDocumentor2/releases/download/v2.9.0/phpDocumentor.phar).

We do not support composer installs in all projects.

**Comment by giovkanata** [comment]
> Please use the provided phar.

This means that will resolve the issue?

> We do not support composer installs in all projects.

In the [installation](https://github.com/phpDocumentor/phpDocumentor2#installation) section it's mentioned at point 2 as supported.

**Comment by jaapio** [comment]
Yes we provide a way to install phpdocumentor via composer. But we won't support all projects. Composer will give you conflicts at some point. That means that we have to upgrade our dependencies and be backwards compatible for older projects. There is no way to accomplish that. 

If you use the phar you don't have a composer dependency. So it won't conflict.

We changed our statement about the installation of php applications like phpdocumentor Version 3 of phpdocumentor won't have composer support when it is released. Applications should be installed stand-alone, and not be part of your project. due to many conflicts we had in the past.

**Comment by giovkanata** [comment]
Thanks for the clarifications @jaapio
