### ISSUE TITLE
Lacking support for grouped use declarations in php 7.0

### ISSUE THREAD

**Issue by adjenks** [phpDocumentor/phpDocumentor2#1828]
phpDocumentor does not support grouped declaration use, a feature of 7.0:
http://php.net/manual/en/language.namespaces.importing.php

I agree with user @ilianiv that this feature should be available as previously outlined here:
https://github.com/phpDocumentor/phpDocumentor2/issues/1801

**Comment by esokullu** [comment]
Yes, and anonymous classes of 7.1 are also not supported.

**Comment by mvriel** [comment]
I agree that we should support grouped declaration uses and I have triaged this item as a bug to be picked up. At this moment I am doing an inventory of the open issues and we will try to address this issue as soon as we can.

As for anonymous classes; this category of syntax is equally troublesome to anonymous functions and we will need to investigate how this can best be resolved; if we even can without complicated constructs. I consider it out of scope for this specific issue and a new issue needs to be opened for this (if that doesn't already exist) to prevent conflating this issue.

**Comment by mvriel** [comment]
Based on my current research an upgrade of the NikiC PHP-Parser dependency is necessary to v2 or even better v3. Unfortunately, these major upgrades also bump the minimal PHP version to 5.4 or 5.5 and this causes a BC break in the project. In order to do this, we would need to bump the major version for phpDocumentor to 3 and we are currently discussing what to do with the current effort for phpDocumentor 3.

As we have a meeting on monday to discuss this I am going to postpone work on this until that meeting has been.

**Comment by adjenks** [comment]
Thank you for the update. Keep up the good work.

**Comment by jaapio** [comment]
I added a test case to show the correct working and processing of grouped namespaces. 
This feature is part of v3 and can be tested with the current version in develop.
