### ISSUE TITLE
Requires phpdocumentor/reflection-docblock 2.0

### ISSUE THREAD

**Issue by ryan7273** [phpDocumentor/phpDocumentor2#1834]
Is there any reason this cannot be updated to include reflection-docblock 3.0? I have been trying to install something with a dependency on 3.0 and cannot do so and keep phpDocumentor installed. Composer does not allow multiple versions of things...

**Comment by jaapio** [comment]
V3 is a complete rewrite. We cannot support both. V3 was planned to be used in a new phpdocumentor which is still work in progress. 

I recommend you to use the phar file instead of installing phpdocumentor via composer. That will solve your issues and allows you to move forward while we are working on an update. We will most likely drop composer support of phpdocumentor in the future.
