### ISSUE TITLE
pear.phpdoc.org unavailable

### ISSUE THREAD

**Issue by jpardoe** [phpDocumentor/phpDocumentor2#1891]
When I visit pear.phpdoc.org I get "503 Service Unavailable".  When I try pear channel-discover pear.phpdoc.org I get "File http://pear.phpdoc.org:80/channel.xml not valid (received: HTTP/1.0 503 Service Unavailable)"  Same error with https.  I tried downloading the release tar archive from github and using pear install phpDocumentor-2.9.0.tgz , but got
Unknown channel "pear.phpdoc.org"
Parsing of package.xml from file "/tmp/pear/temp/pearU8CjAA/package.xml" failed
install failed

**Comment by mvriel** [comment]
This was a temporary failure because the load balancer wasn't pointing to the right server. This issue has long been resolved and as such I am closing this issue

**Comment by smileBeda** [comment]
Interesting. There is still doc referencing it, probably not official one: 
https://zonuexe.github.io/phpDocumentor2-ja/getting-started/installing.html

Got serious troubles installing php-doc. The official doc https://docs.phpdoc.org/3.0/guide/getting-started/installing.html `phive install phpDocumentor` results in a `zsh: command not found: phpdoc` after installing and trying `phpdoc run -d <SOURCE_DIRECTORY> -t <TARGET_DIRECTORY>`

Probably related to the path into which phive puts the documenter.
So I started googling and came here over a few edges 

Thanks for the heads up about PEAR unsupported.

**Comment by mvriel** [comment]
@smileBeda a different issue with the same results has occurred in the mean time. I have just kicked the server (so to speak, not literally) and the website is up again. Though as @ashnazg mentions, we no longer publish new packages to the pear channel, nor actively maintain it anymore, in favour of our PHAR files or by using our official Docker container

**Comment by smileBeda** [comment]
I think the main page is a good location 🤣 
It makes it look "easy", but fact is, if we follow it step by step (at least on darn Macs) we run into `zsh: command not found: phpdoc`, inevitably

From there users start googling. And they end on SO, where stuff is ... well, not the newest. From there you land on those links as I found and mentioned above
So I think a A) very clear how to on the main page and a B) notice in the "install with" that PEAR is not anymore maintained keeps the headache away.
(PS: the instructions differ from homepage to doc to git, so that might also need some unification)

I am using wp parser usually, but now I need to document a pure PHP project, so I have hopes to have this running before end of my day 🤞 

Thanks

**Comment by mvriel** [comment]
If you are able: I definitely recommend the Docker container. Because the Docker container includes plantuml and graphviz preinstalled. 

I am currently working on updating the docs so that @ashnazg and @jaapio can focus on the fun stuff; I'll be sure to review and include your suggestions where applicable!

**Comment by mvriel** [comment]
The first message is because you are on mac; IIRC `$(pwd)` doesn't work on mac but `${PWD}` does. And the second message (where you use the correct notation) means that your Docker Engine is not running.

**Comment by mvriel** [comment]
Thanks for letting me know about the `$(pwd)`; I'll do some digging what notation to use since it may differ between windows, mac and linux

**Comment by mvriel** [comment]
Ah no, mac does know about $(pwd) but it looks like it needs double quotes around it?

**Comment by mvriel** [comment]
I just tried 

```
docker run --rm -v ${PWD}:/data phpdoc/phpdoc:3 src/phpDocumentor/Compiler
```

On the phpDocumentor codebase from Windows/WSL and it seems to document the `src/phpDocumentor/Compiler` folder. Perhaps this is a mac-specific thing? 

And if you tried to run phpdoc with by typing `phpdoc`; I'm afraid docker won't help you out there as you'd need an alias or actual file in your global binaries folder.

I just tried running the command `alias phpdoc="docker run --rm -v ${PWD}:/data phpdoc/phpdoc:3"` and then I can just use `phpdoc` (I abuse ZSH's ability to alias one command to another. Perhaps this will help you?

**Comment by smileBeda** [comment]
Really beautiful BTW, the whole HTML and all there, with TOC etc.

Cool. Better than wp parse (which needs a database, specific post types, etc etc. This is standalone!)

Great work!

**Comment by mvriel** [comment]
Thanks for the feedback and my apologies for the struggle there. I am definitely going to use your experiences to improve that part of the documentation so that the next person will have a much smoother onboarding!

**Comment by smileBeda** [comment]
PS I can see you updated the homepage - and I tried its instructions (using the PHAR).
Worked like a charm, inclusive the instructions on get started about how to make the command globally available.

Good by docker, I did not like you and never will 🤣 

Thanks!
