### ISSUE TITLE
Support of Twig 2.*

### ISSUE THREAD

**Issue by andreyklumchyk** [phpDocumentor/phpDocumentor2#1961]
It would be great to have ability for upgrade Twig at least to the 2.0.* version in projects with phpDocumentor.

## Expected Behavior
Expects that composer json supports 1.3 and  2.* version of Twig.

## Actual Behavior
Currently used Twig version is `~1.3` and it  is little outdated.

If it is not possible for some reasons, please tell when such changes could be made. 
Thanks.

**Comment by Atulin** [comment]
I second it. Nothing worse than having to use outdated dependencies or having to juggle versions for legacy support reasons. Wouldn't've been that bad if I wasn't using Twig in my project, but I am.

And having a choice between PHPDoc and Twig, unfortunately, up-to-date Twig wins.

**Comment by mvriel** [comment]
I have just tried to do the upgrade but because we re-set the Extensions in each pass of the writer an upgrade is not easily doable. This trick is not allowed in Twig 2.

The situation that you describe is why we recommend using the phar file or the docker based setup to generate your documentation. phpDocumentor contains too many dependencies that may conflict with your particular setup for use to accommodate everyone.

Even by upgrading Twig to version 2.0 we may be causing issues for people using Twig 1.3 in their projects.

I had hoped that with a quick upgrade that we would help you out there, but because it takes effort we could use to fix bugs without a direct ROI I am afraid we are unable to do this at this time.

**Comment by FotoXe33** [comment]
So we just cannot use phpdocumentor with composer ? Very nice, good job !!!
And if all our project use composer, we have to install this old and unused pear/pecl to use phpdoc ? Supid choice....
I'll never use again phpdoc so...

**Comment by ashnazg** [comment]
Use the PHARs, Luke...

The PHARs will be with you, always...

Don't underestimate the PHARs...
