### ISSUE TITLE
PHPDoc chokes on PHP 7.1 optional function parameters

### ISSUE THREAD

**Issue by tchapi** [phpDocumentor/phpDocumentor2#1986]
When using PHP7.1 optional parameters syntax, PHPDoc does not parse the file.

## Expected Behavior
This file should be parsed correctly : 

```
<?php
/**
 * Test file
 *
 * @author      tchapi
 */

/**
 * Class Test
 * 
 * This is a test
 * 
 */
class Test
{
    /**
     * For the sake of it
     *
     * @param string $test (optional) whatever
     *
     * @return void
     */
    public function testme (?string $test): void
    {
        var_dump($test);
    }
}
```

## Actual Behavior
`Parse Error: Syntax error, unexpected '?', expecting T_VARIABLE on line 23  No summary was found for this file`

and nothing is thus parsed in the file.

## Steps to Reproduce the Problem

  1. Parse the file above
  2. :boom: 

## Your environment

PHP 7.2.6 (cli) (built: May 25 2018 06:18:07) ( NTS )
phpDocumentor version v2.9.0

## Possible resolution

If PHPDoc does not support this feature yet, it could be nice to change the requirements ('PHP 7.0 or higher' in the README) to 'PHP 7.0' so that it's clear for people that stumble on this problem

**Comment by jaapio** [comment]
Our develop branch does support php7. So that readme is correct. Master shows that we are able to run on php5.3 and higher. There is no final release yet with support for these php 7+ features. The current version required a lot of work to introduce support for php7. 

Closing this because there are a number of other issues according this kind of issues.
