### ISSUE TITLE
Useless .phar signing

### ISSUE THREAD

**Issue by AnrDaemon** [phpDocumentor/phpDocumentor2#2025]
Anybody could create a garbage .phar and place a matching .pubkey next to it.
It adds absolutely no security, but increases maintenance cost by a lot.

**Comment by Gaurav-Punjabi** [comment]
So exactly what is the issue?

**Comment by jaapio** [comment]
I'm closing this issue since it isn't a question, or issue report.

By signing the phar with a private key. And publish the public we make sure that nobody modified the phar. Beside that you can verify that we published the phar.

I do agree that this isn't a water tight solution. But I disagree with you that it increases the maintenance costs. Have a look at phive.io for a good way to install phpdocumentors phar in a automated way.

Beside that phpdocumentor can be installed using docker, composer or just git clone. So it it does not fit your needs using the phar please try an other install method.

**Comment by AnrDaemon** [comment]
I solved it. Of course.
But rest assured, this is going to be a recurrent issue.
You can publish a detached signature for verification, it will be as efficient as signing the .phar for verification, but people would be able to at least run the .phar without all the idiotic issues of carrying pubkeys around, ensuring that necessary hashing methods available in PHP, and so on. And I'm not exaggerating. Just google "phar signing" and see how many problems it causes to an end user. I've read them all, until I've finally found and solved my issue.

**Comment by jaapio** [comment]
For future reference it would be nice if you could post the solution here.

Just remember that you spend just one evening to solve the problem. And we as maintainers spend multiple evenings, days weeks to make it possible for you to just run phpdocumentor in just one evening. You are getting it for free.

**Comment by AnrDaemon** [comment]
Solution? I've had to remove stray space at the end of .pubkey file name.
