### ISSUE TITLE
Source code displays "Error: File does not exist or is empty"

### ISSUE THREAD

**Issue by ghost** [phpDocumentor/phpDocumentor2#2074]
## Expected Behavior
Source code to appear when clicking the source code icon.

## Actual Behavior
Displays message: "Error: File does not exist or is empty". In addition if I look at the files in /files/includes/ they are all empty files and have extension .php.txt.

![Screenshot from 2019-03-15 19-01-34](https://user-images.githubusercontent.com/47676272/54455920-cc2f7d00-4754-11e9-9483-71571463b124.png)

## Steps to Reproduce the Problem

  1. Using phpDocumentor dev-master
  2. Compile source code using command:
`sudo vendor/bin/phpdoc -d ./ -t /home/username/Desktop/apidocs --ignore "vendor/,includes/libraries/"`

## Your environment

* XAMPP
* dev-master
* Composer
* PHP 7.2.10
* Ubuntu 18.04

**Comment by mvriel** [comment]
Usually, this issue is caused because you try to view the documentation from a local file, i.e. from `file://`. Because the source files are included using an XHR request they are blocked by the browser.

I recommend for this feature, to open the documentation using a web server (even if it is php's local web server). I would like to fix this issue in the future, but to prevent performance issues this is the solution we are currently working with.

If the above is not applicable in your situation you can also try to add the `--sourcecode` flag; some versions of phpDocumentor 2.x were adjusted not to generate the source code by default. In phpDocumentor 3 on develop this has been refined and the source button is not even visible if the source is not included when generating the documentation
