### ISSUE TITLE
Suggestion: new @provides param

### ISSUE THREAD

**Issue by mityukov** [phpDocumentor/phpDocumentor2#2087]
Sometimes, there are methods, that should not be called by client code directly. Instead, they "provide" some property or a method.

For example, here's a Laravel model I'm trying to "properly" document:
```php
/**
 * // Scopes
 * @method \Illuminate\Database\Eloquent\Builder active() Add "Account is active and not expired" scope to the query builder
 *
 * // Accessors
 * @property-read boolean $is_active Account is active and not expired
 */
class Account extends Model
{
    /**
     * Laravel Scope. Don't call in client code!
     * @ignore
     * @see \App\Account::active()
     */
    public function scopeActive($query)
    {
        return $query->where('active', true)
            ->where(function ($query) {
                $query->whereNull('expires_at')
                    ->orWhere('expires_at', '>=', date('Y-m-d', time()));
            });
    }

    /**
     * Laravel Accessor. Don't call in client code!
     * @ignore
     * @see \App\Account::$is_active
     */
    public function getIsActiveAttribute()
    {
        return $this->active && ! $this->is_expired;
    }
}
```

It would be of great help If I could use one of these syntaxes instead:
```php
/**
 * // Scopes
 * @method \Illuminate\Database\Eloquent\Builder active() Add "Account is active and not expired" scope to the query builder
 *
 * // Accessors
 * @property-read boolean $is_active Account is active and not expired
 */
class Account extends Model
{
    /**
     * @provides \App\Account::active()
     */
    public function scopeActive($query)
    {
        return $query->where('active', true)
            ->where(function ($query) {
                $query->whereNull('expires_at')
                    ->orWhere('expires_at', '>=', date('Y-m-d', time()));
            });
    }

    /**
     * @provides \App\Account::$is_active
     */
    public function getIsActiveAttribute()
    {
        return $this->active && ! $this->is_expired;
    }
}
```

--OR-- shorter (or, "inline") form:

```php
class Account extends Model
{
    /**
     * @provides \Illuminate\Database\Eloquent\Builder active() Add "Account is active and not expired" scope to the query builder
     */
    public function scopeActive($query)
    {
        return $query->where('active', true)
            ->where(function ($query) {
                $query->whereNull('expires_at')
                    ->orWhere('expires_at', '>=', date('Y-m-d', time()));
            });
    }

    /**
     * @provides boolean $is_active Account is active and not expired
     */
    public function getIsActiveAttribute()
    {
        return $this->active && ! $this->is_expired;
    }
}
```

Expected behavior for `@provides`:

1. Documentor doesn't document the method/property itself. Only the property it refers to..

2. Intellisense does not suggest such methods/properties outside the class itself (i.e., in client code). O, it suggests them, but marking as "providing", with the explanation on what this method provides.

**Comment by jaapio** [comment]
I don't really get your suggestion. We do have a `@method` tag which is the way to go to define magic methods on a certain object. 

Without any knowledge of laravel and its way to implement this, this feels like a lot of magic. Which is hidden by some obscure docblock to make your editor aware of the magic you are trying to do.

Beside that if we would add such a tag in phpdocumentor the editors wouldn't support it automatically.

**Comment by mityukov** [comment]
The goal is to suggest/document `$model->is_active`, while not suggesting `$model->getIsActiveAttribute()`. Another goal: to simplify the "markup" (see the latest "inline" code snippet).

> Beside that if we would add such a tag in phpdocumentor the editors wouldn't support it automatically.

I know, I know… But they definitely won't support anything that's not supported by phpdocumentor in the first place :-(

**Comment by boyueking** [comment]
发自我的华为手机-------- 原始邮件 --------主题：[phpDocumentor/phpDocumentor2] Suggestion: new @provides param (#2087)发件人：Vladimir Mityukov 收件人：phpDocumentor/phpDocumentor2 抄送：Subscribed Sometimes, there are methods, that should not be called by client code directly. Instead, they "provide" some property or a method.
For example, here's a Laravel model I'm trying to "properly" document:
/**
 * // Accessors
 * @property-read boolean $is_active Account is active and not expired
 *
 * // Scopes
 * @method \Illuminate\Database\Eloquent\Builder active() Add "Account is active and not expired" scope to the query builder
 */
class Account extends Model
{
    /**
     * Laravel Scope. Don't call in client code!
     * @ignore
     * @see \App\Account::active()
     */
    public function scopeActive($query)
    {
        return $query->where('active', true)
            ->where(function ($query) {
                $query->whereNull('expires_at')
                    ->orWhere('expires_at', '>=', date('Y-m-d', time()));
            });
    }

    /**
     * Laravel Accessor. Don't call in client code!
     * @ignore
     * @see \App\Account::$is_active
     */
    public function getIsActiveAttribute()
    {
        return $this->active && ! $this->is_expired;
    }
}
It would be of great help If I could use one of these syntaxes instead:
/**
 * // Accessors
 * @property-read boolean $is_active Account is active and not expired
 *
 * // Scopes
 * @method \Illuminate\Database\Eloquent\Builder active() Add "Account is active and not expired" scope to the query builder
 */
class Account extends Model
{
    /**
     * @provides \App\Account::active()
     */
    public function scopeActive($query)
    {
        return $query->where('active', true)
            ->where(function ($query) {
                $query->whereNull('expires_at')
                    ->orWhere('expires_at', '>=', date('Y-m-d', time()));
            });
    }

    /**
     * @provides \App\Account::$is_active
     */
    public function getIsActiveAttribute()
    {
        return $this->active && ! $this->is_expired;
    }
}
--OR-- shorter (or, "inline") form:
class Account extends Model
{
    /**
     * @provides \Illuminate\Database\Eloquent\Builder active() Add "Account is active and not expired" scope to the query builder
     */
    public function scopeActive($query)
    {
        return $query->where('active', true)
            ->where(function ($query) {
                $query->whereNull('expires_at')
                    ->orWhere('expires_at', '>=', date('Y-m-d', time()));
            });
    }

    /**
     * @provides boolean $is_active Account is active and not expired
  \App\Account::active()
     */
    public function getIsActiveAttribute()
    {
        return $this->active && ! $this->is_expired;
    }
}
Expected behavior for @provides:

Documentor doesn't document the method/property itself. Only the property it refers to..

Intellisense does not suggest such methods/properties outside the class itself (i.e., in client code). O, it suggests them, but marking as "providing", with the explanation on what this method provides.
