### ISSUE TITLE
 [Twig\Error\SyntaxError]   Unknown "sort_asc" filter.

### ISSUE THREAD

**Issue by Jhonatan256** [phpDocumentor/phpDocumentor2#2088]
Execute code C:\composer\vendor\bin\phpdoc.php.bat project:run -d ./controlador -t ./documentacion  in the root folder of the project:
![Anotación 2019-05-21 184008](https://user-images.githubusercontent.com/25461820/58137452-e758b600-7bf7-11e9-81b7-d8a23dde1cfa.png)

at the end of the execution does not generate the index.html file and gives the following error:
![Anotación 2019-05-21 184103](https://user-images.githubusercontent.com/25461820/58137475-06efde80-7bf8-11e9-9e1b-d008c05ae063.png)

Version PHP: 7.3

**Comment by NesCafe62** [comment]
What phpdocumentor version are you using? Did you installed it with composer?

**Comment by Jhonatan256** [comment]
> ¿Qué versión de phpdocumentor estás usando? ¿Lo instalaste con el compositor?

Lo instale con composer y la veersion

**Comment by Jhonatan256** [comment]
installed with composer.
version phpdocumentor 2.0.0

Now I use the configuration file phpdoc.xml just to analyze a script:


![image](https://user-images.githubusercontent.com/25461820/58201853-bdf16600-7c9b-11e9-8e99-4ab3ae1b3ab6.png)


but the error persists:
![image](https://user-images.githubusercontent.com/25461820/58201861-c3e74700-7c9b-11e9-9cfe-dfbdd158fa63.png)

**Comment by mvriel** [comment]
That filter is added using phpDocumentor's own Twig Extension. If you get the message that if cannot be found I get the feeling that this has to do with including it using composer.

Unfortunately, it is too complex for us to support composer-based installations because phpDocumentor is an application using the Symfony Framework as a basis. There are countless packages that can conflict or otherwise cause issues.

Can I ask you to try again using one of the other installation options, such as Docker or Phar?

**Comment by jaapio** [comment]
Closing because there hasn't been any action on this item by the author for 2 months now.
