### ISSUE TITLE
Source code displays "Error: File does not exist or is empty" - nothink work

### ISSUE THREAD

**Issue by kofston** [phpDocumentor/phpDocumentor2#2091]
## Actual Behavior
J can not see my code after click source view near my method 
i all time have this comunicate when i want show my method code:

![image](https://user-images.githubusercontent.com/50779251/58812857-f3466e00-8622-11e9-869e-99ee2799f003.png)

How i can show code?
What tags i need?

* Version used: 2.8.4
* Install method PHAR
* php version 7.3
* Operating system and version (Windows 10):

**Comment by mvriel** [comment]
Usually, this message appears because you are viewing your documentation from `file://` instead from a webserver. The code for a file is loaded using an XHR request, and local files are blocked by browsers from retrieving other files using XHR requests.

In phpDocumentor 3 alpha 3 there has been an issue with including the source; but 2.8.4 should not suffer from this.
